jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'

spring:
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/wwyp #change this to your database url
    username: root #change this to your database username
    password: root #change this to your database password
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    repositories:
      bootstrap-mode: default

logging:
  level:
    org:
      hibernate:
        type: trace
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG
